poolinroot4.err4 line 4: pool declared outside of network
